services:

  # --------------------------------------------------------
  # METADATA SERVER (File Metadata Management)
  # --------------------------------------------------------
  md-server:
    # --- Identity ---
    image: seafileltd/seafile-md-server:${MD_TAG}
    container_name: ${CONTAINER_NAME_MD_SERVER}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_healthy

    # --- Security ---
    security_opt:
      - no-new-privileges:true

    # --- Configuration ---
    environment:
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - SEAFILE_MYSQL_DB_HOST=db
      - SEAFILE_MYSQL_DB_PORT=3306
      - SEAFILE_MYSQL_DB_USER=${DB_USER}
      - SEAFILE_MYSQL_DB_PASSWORD=${SEAFILE_MYSQL_DB_PASSWORD}
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=seafile_db
      - SEAFILE_LOG_TO_STDOUT=false
      - MD_PORT=8084
      - MD_LOG_LEVEL=${MD_LOG_LEVEL:-info}
      - MD_MAX_CACHE_SIZE=${MD_MAX_CACHE_SIZE:-1GB}
      - MD_CHECK_UPDATE_INTERVAL=30m
      - MD_FILE_COUNT_LIMIT=${MD_FILE_COUNT_LIMIT:-100000}
      - MD_STORAGE_TYPE=${MD_STORAGE_TYPE:-disk}
      - SEAF_SERVER_STORAGE_TYPE=${SEAF_SERVER_STORAGE_TYPE:-disk}
      - CACHE_PROVIDER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    # --- Storage ---
    volumes:
      - ./volumes/seafile-data:/shared

    # --- Networking ---
    networks:
      - app-internal

networks:
  app-internal:
    name: ${COMPOSE_PROJECT_NAME}-internal
