services:

  # --------------------------------------------------------
  # NOTIFICATION SERVER (Real-time File Change Notifications)
  # --------------------------------------------------------
  notification-server:
    # --- Identity ---
    image: seafileltd/notification-server:${NOTIFICATION_TAG}
    container_name: ${CONTAINER_NAME_NOTIFICATION}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_healthy

    # --- Security ---
    security_opt:
      - no-new-privileges:true

    # --- Configuration ---
    entrypoint: ["/bin/sh", "/config/entrypoint.sh", "/scripts/enterpoint.sh"]
    environment:
      - SEAFILE_MYSQL_DB_HOST=db
      - SEAFILE_MYSQL_DB_PORT=3306
      - SEAFILE_MYSQL_DB_USER=${DB_USER}
      - SEAFILE_MYSQL_DB_CCNET_DB_NAME=ccnet_db
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=seafile_db
      - SEAFILE_LOG_TO_STDOUT=false
      - NOTIFICATION_SERVER_LOG_LEVEL=${NOTIFICATION_LOG_LEVEL:-info}
    secrets:
      - SEAFILE_DB_PWD
      - JWT_KEY

    # --- Storage ---
    volumes:
      - ./config/entrypoint.sh:/config/entrypoint.sh:ro
      - ./volumes/seafile-data/seafile/logs:/shared/seafile/logs

    # --- Networking ---
    networks:
      - app-internal

networks:
  app-internal:
    name: ${COMPOSE_PROJECT_NAME}-internal
