services:

  # --------------------------------------------------------
  # THUMBNAIL SERVER (image/video thumbnails – optional)
  # --------------------------------------------------------
  thumbnail-server:
    # --- Identity ---
    image: ${THUMBNAIL_SERVER_IMAGE}
    container_name: ${CONTAINER_NAME_THUMBNAIL}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      seafile:
        condition: service_healthy

    # --- Security ---
    security_opt:
      - no-new-privileges:true

    # --- Configuration ---
    environment:
      TIME_ZONE: ${TIMEZONE}
      SEAFILE_MYSQL_DB_HOST: db
      SEAFILE_MYSQL_DB_PORT: "3306"
      SEAFILE_MYSQL_DB_USER: ${SEAFILE_DB_USER}
      SEAFILE_MYSQL_DB_PASSWORD_FILE: /run/secrets/SEAFILE_DB_PWD
      SEAFILE_MYSQL_DB_CCNET_DB_NAME: ccnet_db
      SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: seafile_db
      NON_ROOT: "false"
      JWT_PRIVATE_KEY_FILE: /run/secrets/JWT_KEY
      SEAFILE_LOG_TO_STDOUT: "false"
      SITE_ROOT: /
      INNER_SEAHUB_SERVICE_URL: http://seafile
      THUMBNAIL_IMAGE_ORIGINAL_SIZE_LIMIT: ${THUMBNAIL_SIZE_LIMIT}
    secrets:
      - SEAFILE_DB_PWD
      - JWT_KEY

    # --- Storage ---
    volumes:
      - ./volumes/seafile-data:/shared

    # --- Networking ---
    networks:
      - proxy-public
      - app-internal

    # --- Traefik ---
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-thumbnail.rule=Host(`${APP_TRAEFIK_HOST}`) && PathPrefix(`/thumbnail`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-thumbnail.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-thumbnail.tls=true"
      #- "traefik.http.routers.${COMPOSE_PROJECT_NAME}-thumbnail.tls.certresolver=${APP_TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-thumbnail.tls.options=${APP_TRAEFIK_TLS_OPTION}@file"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-thumbnail.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy-public"

# --------------------------------------------------------
# NETWORKS (shared with seafile-server.yml)
# --------------------------------------------------------
networks:
  proxy-public:
    external: true

  app-internal:
    name: ${COMPOSE_PROJECT_NAME}-internal
    internal: true

# --------------------------------------------------------
# SECRETS (shared with seafile-server.yml)
# --------------------------------------------------------
secrets:
  SEAFILE_DB_PWD:
    file: ./secrets/seafile_db_pwd.txt
  JWT_KEY:
    file: ./secrets/jwt_key.txt
