#!/usr/bin/env python3
"""
Lifecycle report generator for secure-docker-blueprint.

Derives the per-stack lifecycle defined in docs/standards/status-model.md and
writes it to LIFECYCLE.md. Every state is measured from an artefact. Nothing is
typed into a table, and LIFECYCLE.md is never hand-edited.

The lifecycle serves a maintainer deciding what to work on. It carries no
promise to an operator — that belongs on the site, as evidence and named gaps.

States, and what establishes each:
  scaffolded        a compose file exists, or the stack is host-installed
  verified          `Last verified: DATE (vX.Y.Z)` in <stack>/UPSTREAM.md
  baseline-aligned  verified, and both baseline checkers pass
  ops-proven        baseline-aligned, and the stack appears in the rehearsal log
                    of backup/borgmatic/RESTORE.md

A date without a version stays at `scaffolded`. Which version was checked is
what makes the claim usable later; a bare date says only that someone looked.

Baseline alignment is taken from the exit codes of check-baseline.py and
check-structure.py, run once per invocation. A failure in either withholds
`baseline-aligned` from every stack in that run rather than from the one that
caused it — the two checkers truncate their own output, so a per-stack answer
cannot be read back reliably. Both block CI, so a committed state never carries
a partial answer.

Other owners (see status-model.md):
  pinned version  <stack>/.env.example  (APP_TAG, else APP_IMAGE, else first pin)
  backup/restore  <stack>/README.md     (presence of the corresponding section)

Consistency rules (--check):

FAIL:
  stale-report         LIFECYCLE.md or lifecycle.json differs from the sources
  unknown-stack        the rehearsal log names a stack that does not exist

WARN — evidence probably exists, the record is in the old shape:
  legacy-stamp         the pre-v0.5.1 `Last checked: DATE` field instead of
                       `Last verified: DATE (vX.Y.Z)`. Converting it asserts
                       that evidence is real, so it is never automatic.
  backup-docs-split    UPSTREAM.md documents the backup or restore procedure as
                       well. Two owners for one fact — and because this report
                       only reads the README, the stack shows up as "missing"
                       and invites a third copy. A pointer there is fine.

Usage:
  python3 scripts/ci/lifecycle-report.py            # report to stdout
  python3 scripts/ci/lifecycle-report.py --write    # regenerate LIFECYCLE.md
  python3 scripts/ci/lifecycle-report.py --check [github-summary-path]

--check exits 1 on FAIL only; the default and --write modes otherwise exit 0.
Every mode exits 2 without writing when the baseline checkers cannot be run at
all — see BaselineUndetermined for why that is not the same as them failing.
"""

import importlib.util
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

CATEGORIES = ["core", "apps", "business", "monitoring", "backup"]

# The lifecycle, weakest first. A stack holds the highest state it establishes.
STATES = ["scaffolded", "verified", "baseline-aligned", "ops-proven"]

# Stacks that are structurally exempt, with the reason.
EXCEPT = {"apps/_reference": "the canonical reference itself"}

# Rules that report drift without blocking CI.
WARN_RULES = {"legacy-stamp", "backup-docs-split"}

# `Last verified: 2026-07-29 (34.0.2-fpm-alpine)` — the version in parentheses
# is what separates this from the legacy field.
ANCHORED = re.compile(
    r"Last\s+verified:\s*(\d{4}-\d{2}-\d{2})\s*\(([^)]+)\)", re.I
)
VERIFIED = re.compile(r"Last\s+verified:\s*(\d{4}-\d{2}-\d{2})", re.I)
CHECKED = re.compile(r"Last\s+checked:\s*(\d{4}-\d{2}-\d{2})", re.I)
SECTION = re.compile(r"^#{2,4}\s+.*\b(backup|restore)\b", re.I)

RESTORE_LOG = Path("backup/borgmatic/RESTORE.md")
# A rehearsal row: | date | `apps/nextcloud` | … | … | Pass | … |
REHEARSAL = re.compile(
    r"^\|\s*\d{4}-\d{2}-\d{2}\s*\|\s*`([a-z0-9/_-]+)`\s*\|.*?\|\s*Pass\s*\|",
    re.I,
)

MARKER = "<!-- generated by scripts/ci/lifecycle-report.py — do not edit by hand -->"


def read(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def plain(text: str) -> str:
    """Drop markdown emphasis so `**Last verified:**` matches like plain text."""
    return text.replace("*", "")


class BaselineUndetermined(RuntimeError):
    """A baseline checker could not run, which is not the same as failing.

    Both outcomes leave this script without a passing checker, and treating them
    alike is what makes the failure dangerous: an answer of "no stack is
    baseline-aligned" is a legitimate finding, while "I could not ask" is an
    absent one. Written out, the two produce a byte-identical report — every
    stack demoted, `ops-proven` gone, and nothing on the page saying why.
    """


def baseline_ok() -> bool:
    """True when both baseline checkers pass.

    Run once per invocation. Their own output truncates its finding lists, so a
    per-stack answer cannot be read back from it — the exit code is what is
    reliable. A failure withholds `baseline-aligned` from every stack in the
    run. Both checkers block CI, so no committed state depends on that.

    Raises `BaselineUndetermined` where the exit code establishes nothing: a
    missing dependency, a checker that could not be started, or one that died on
    a traceback. A Python traceback also exits 1, so the exit code alone cannot
    separate "found violations" from "crashed" — the stderr is what does.
    """
    if importlib.util.find_spec("yaml") is None:
        raise BaselineUndetermined(
            f"PyYAML is not importable by {Path(sys.executable).name} — the "
            "checkers need it to read compose files. Install it with "
            "`pip install --require-hashes -r scripts/ci/requirements.txt`"
        )

    here = Path(__file__).parent
    for script in ("check-baseline.py", "check-structure.py"):
        try:
            done = subprocess.run(
                [sys.executable, str(here / script)],
                capture_output=True, text=True, timeout=180,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            raise BaselineUndetermined(f"{script} could not be run: {exc}") from exc
        if done.returncode != 0 and "Traceback (most recent call last)" in done.stderr:
            last = done.stderr.strip().splitlines()[-1]
            raise BaselineUndetermined(
                f"{script} exited on an exception rather than a finding: {last}"
            )
        if done.returncode != 0:
            return False
    return True


def restored_stacks() -> tuple[set[str], list[str]]:
    """(stack keys with a passing restore, keys named that do not exist).

    Read from the rehearsal log, which is where the evidence is produced — the
    archive, the scope, the result and the numbers are recorded together.
    """
    found, unknown = set(), []
    for line in read(RESTORE_LOG).splitlines():
        m = REHEARSAL.match(line)
        if not m:
            continue
        key = m.group(1)
        if Path(key).is_dir():
            found.add(key)
        else:
            unknown.append(key)
    return found, unknown


def has_compose(stack: Path) -> bool:
    """True for a Compose stack — including ones split across per-component files."""
    return any(stack.glob("*.yml"))


def pinned_version(stack: Path) -> str:
    """The stack's primary image pin, in `VAR=value` form."""
    if not has_compose(stack):
        return "*host-installed*"
    env = read(stack / ".env.example")
    if not env:
        return "—"
    pins: dict[str, str] = {}
    for raw in env.splitlines():
        line = raw.strip()
        if line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip()
        if key.endswith(("_TAG", "_IMAGE")) and value:
            pins.setdefault(key, value)
    for preferred in ("APP_TAG", "APP_IMAGE"):
        if preferred in pins:
            return f"`{preferred}={shorten(pins[preferred])}`"
    if pins:
        key = next(iter(pins))
        return f"`{key}={shorten(pins[key])}`"
    return "—"


def shorten(value: str) -> str:
    """Abbreviate a sha256 digest so it does not blow out the table width."""
    return re.sub(r"(sha256:[0-9a-f]{12})[0-9a-f]+", r"\1…", value)


def last_verified(stack: Path) -> tuple[str, bool, str]:
    """(date-or-dash, is_current_format, version-or-empty).

    The version is what the date refers to. A pin that moved afterwards leaves
    the two describing different things, so both are carried rather than the
    date alone. Legacy `Last checked:` is not current format.
    """
    text = plain(read(stack / "UPSTREAM.md"))
    if not text:
        return "—", False, ""
    m = ANCHORED.search(text)
    if m:
        return m.group(1), True, m.group(2).strip()
    # A date without the version in parentheses names no anchor, so it does not
    # establish `verified` — same treatment as the legacy field.
    m = VERIFIED.search(text)
    if m:
        return f"{m.group(1)} ⚠️", False, ""
    m = CHECKED.search(text)
    if m:
        return f"{m.group(1)} ⚠️", False, ""
    return "—", False, ""


# Stacks for which a `## Backup` section would be circular: the tool that performs
# the backup cannot meaningfully describe how to back itself up with itself. What
# protects them is documented in their own terms — for borgmatic, the exported
# repository key under `## Keys`.
NO_BACKUP_SECTION = {
    "backup/borgmatic": "it is the backup tool — see its `## Keys` section",
}


def doc_sections(stack: Path) -> tuple[str, str]:
    """(backup docs, restore docs).

    Counted either as a section in the stack README or as a dedicated file —
    `backup/borgmatic` keeps its procedure in RESTORE.md rather than a heading.
    """
    if str(stack) in NO_BACKUP_SECTION:
        _, restore = doc_sections_raw(stack)
        return "n/a", restore

    return doc_sections_raw(stack)


def backup_docs_elsewhere(stack: Path) -> bool:
    """True when UPSTREAM.md carries backup/restore *procedure*, not a pointer.

    The backup section belongs in the stack README — that is where the per-app
    pattern lives and the only place this script looks. An UPSTREAM.md that also
    documents the procedure is a second owner for the same fact, and because it is
    invisible here it reads as "missing" and invites someone to write a third copy.
    That happened to `apps/vaultwarden` and `business/invoiceninja`.

    A pointer back to the README is fine; a table or a command block is not.
    """
    lines = read(stack / "UPSTREAM.md").splitlines()
    inside = False
    for line in lines:
        if line.startswith("#"):
            inside = bool(SECTION.match(line))
            continue
        if inside and (line.startswith("```") or line.startswith("|")):
            return True
    return False


def doc_sections_raw(stack: Path) -> tuple[str, str]:
    has = {
        "backup": (stack / "BACKUP.md").exists(),
        "restore": (stack / "RESTORE.md").exists(),
    }
    for line in read(stack / "README.md").splitlines():
        m = SECTION.match(line)
        if m:
            has[m.group(1).lower()] = True
    return (
        "documented" if has["backup"] else "missing",
        "documented" if has["restore"] else "missing",
    )


def collect() -> tuple[list[dict], list[dict]]:
    """Return (rows, problems). Each row's state is measured, not read back."""
    rows: list[dict] = []
    problems: list[dict] = []

    baseline = baseline_ok()
    restored, unknown = restored_stacks()
    for key in unknown:
        problems.append({
            "rule": "unknown-stack", "stack": key,
            "detail": f"named in {RESTORE_LOG} but no such directory exists",
        })

    if not baseline:
        problems.append({
            "rule": "baseline-failing", "stack": "—",
            "detail": "a baseline checker reported findings, so no stack is "
                      "reported as baseline-aligned in this run",
        })

    for category in CATEGORIES:
        cat_dir = Path(category)
        if not cat_dir.is_dir():
            continue

        for stack in sorted(p for p in cat_dir.iterdir() if p.is_dir()):
            key = f"{category}/{stack.name}"
            if key in EXCEPT:
                continue
            # A stack qualifies on its own artefacts: compose files — including
            # stacks split across one file per component — or an UPSTREAM.md,
            # which is what a host-installed component like backup/borgmatic has
            # instead.
            if not has_compose(stack) and not (stack / "UPSTREAM.md").is_file():
                continue

            if backup_docs_elsewhere(stack):
                problems.append({
                    "rule": "backup-docs-split", "stack": key,
                    "detail": "UPSTREAM.md documents the backup or restore procedure "
                              "as well — one owner per fact; the README is the one "
                              "this report reads. Leave a pointer there instead",
                })

            verified, current_format, verified_version = last_verified(stack)

            state = "scaffolded"
            if current_format:
                state = "verified"
                if baseline:
                    state = "baseline-aligned"
                    if key in restored:
                        state = "ops-proven"

            if verified != "—" and not current_format:
                problems.append({
                    "rule": "legacy-stamp", "stack": key,
                    "detail": f"carries the pre-v0.5.1 `Last checked: "
                              f"{verified.split()[0]}` — stays at `scaffolded` "
                              f"until converted to `Last verified: DATE (vX.Y.Z)` "
                              f"against confirmed evidence",
                })

            if key in restored and state != "ops-proven":
                problems.append({
                    "rule": "legacy-stamp", "stack": key,
                    "detail": f"a passing restore is logged in {RESTORE_LOG}, but "
                              f"the stack is only `{state}` — it needs a version-"
                              f"anchored verification date to reach ops-proven",
                })

            backup_docs, restore_docs = doc_sections(stack)
            rows.append({
                "stack": key, "category": category, "state": state,
                "pinned": pinned_version(stack), "verified": verified,
                "verified_version": verified_version,
                "backup": backup_docs, "restore": restore_docs,
                "local": "✅" if (stack / "docker-compose.local.yml").exists() else "—",
            })

    return rows, problems


def render_json(rows: list[dict]) -> str:
    """The same facts as LIFECYCLE.md, for anything that renders them.

    The site does not show the lifecycle: a development state is a maintainer's
    answer, and a visitor's question is what has been established about this
    stack and what has not. The site reads the evidence fields — the verified
    date and version, and the backup and restore documentation — and states the
    gaps in its own words.
    """
    payload = {
        r["stack"]: {
            "state": r["state"],
            # LIFECYCLE.md renders this as markdown; data carries the value.
            "pinned": r["pinned"].strip("`*"),
            # The ⚠️ marks a date with no version anchor; the site wants the
            # date alone and the fact separately.
            "verified": r["verified"].replace(" ⚠️", ""),
            "verified_anchored": "⚠️" not in r["verified"] and r["verified"] != "—",
            # What the date refers to. Where the pin has moved on since, the
            # site must not present the current pin as the verified one.
            "verified_version": r["verified_version"],
            "backup_docs": r["backup"],
            "restore_docs": r["restore"],
            "local_stack": r["local"],
        }
        for r in rows
    }
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def strip_stamp(text: str) -> str:
    """The report without its generation date.

    The date says when the file was written, not what it says. Comparing it
    would make the freshness check fail for everyone whose clock is ahead of
    the runner's — a commit made at 01:00 CEST carries tomorrow's date while
    CI, in UTC, is still on today's. That is a two-hour window every night in
    which a correct report is reported stale.
    """
    return "\n".join(
        line for line in text.splitlines() if not line.startswith("Generated ")
    )


def render(rows: list[dict]) -> str:
    # UTC, so the file a contributor generates matches the one CI generates.
    today = datetime.now(timezone.utc).date().isoformat()
    counts: dict[str, int] = {}
    for r in rows:
        counts[r["state"]] = counts.get(r["state"], 0) + 1
    summary = " · ".join(
        f"{counts.get(k, 0)} {k}" for k in reversed(STATES) if counts.get(k)
    )

    out = [
        "# Lifecycle Overview",
        "",
        MARKER,
        "",
        f"Generated {today} from the sources named in "
        + "[`docs/standards/status-model.md`](docs/standards/status-model.md). "
        + "**Do not edit by hand** — run `python3 scripts/ci/lifecycle-report.py --write`.",
        "",
        f"{len(rows)} stacks: {summary}. "
        + f"{sum(1 for r in rows if r['local'] == '✅')} carry a local test stack.",
        "",
        "This is the maintainer's view: what has been established about each "
        + "stack. It makes no statement about whether a stack suits a given "
        + "deployment.",
        "",
        "## What the columns mean",
        "",
        "- **State** — `scaffolded` · `verified` · `baseline-aligned` · "
        + "`ops-proven`, each measured from an artefact. See "
        + "[`status-model.md`](docs/standards/status-model.md).",
        "- **Last verified** — from the stack's `UPSTREAM.md`. A ⚠️ marks a date "
        + "with no version in parentheses, which names no anchor and leaves the "
        + "stack at `scaffolded`.",
        "- **Local** — whether the stack carries "
        + "`docker-compose.local.yml`, which runs it on one machine without a "
        + "proxy, DNS or certificate. A `—` marks a stack that shows nothing run "
        + "alone. See [`compose-structure.md`](docs/standards/compose-structure.md#local-test-stack).",
        "- **Backup / Restore docs** — whether the stack README has such a "
        + "section. Says nothing about whether either was performed; that is what "
        + "`ops-proven` records. `n/a` marks a stack where the section would be "
        + "circular — the backup tool cannot describe backing itself up with "
        + "itself.",
        "",
    ]

    for category in CATEGORIES:
        group = [r for r in rows if r["category"] == category]
        if not group:
            continue
        out += [
            f"## `{category}/`",
            "",
            "| Stack | State | Pinned | Last verified | Local | Backup docs | Restore docs |",
            "|---|---|---|---|---|---|---|",
        ]
        for r in group:
            out.append(
                f"| [`{r['stack']}`]({r['stack']}/) | `{r['state']}` "
                f"| {r['pinned']} | {r['verified']} | {r['local']} "
                f"| {r['backup']} | {r['restore']} |"
            )
        out.append("")

    out += [
        "## Source of truth",
        "",
        "- Stack implementation: the stack's `docker-compose.yml` + `.env.example`.",
        "- Lifecycle procedure: the stack's `README.md` and `UPSTREAM.md`.",
        "- Restore evidence: [`backup/borgmatic/RESTORE.md`]"
        + "(backup/borgmatic/RESTORE.md#rehearsal-log).",
        "- Security baseline definition: [`docs/standards/security-baseline.md`]"
        + "(docs/standards/security-baseline.md).",
        "- State definitions and ownership: [`docs/standards/status-model.md`]"
        + "(docs/standards/status-model.md).",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    args = sys.argv[1:]
    mode = "report"
    if "--write" in args:
        mode = "write"
        args.remove("--write")
    elif "--check" in args:
        mode = "check"
        args.remove("--check")

    if not Path("README.md").exists():
        print("error: run from the repository root", file=sys.stderr)
        return 2

    try:
        rows, problems = collect()
    except BaselineUndetermined as exc:
        print(f"  ❌ cannot establish any stack's state: {exc}", file=sys.stderr)
        print("     Nothing written — a report produced without the baseline "
              "checkers would demote every stack and look exactly like a clean "
              "run that found nothing.", file=sys.stderr)
        return 2

    generated = render(rows)
    target = Path("LIFECYCLE.md")

    generated_json = render_json(rows)
    json_target = Path("site/src/data/lifecycle.json")

    if mode == "write":
        target.write_text(generated, encoding="utf-8")
        json_target.parent.mkdir(parents=True, exist_ok=True)
        json_target.write_text(generated_json, encoding="utf-8")
        print(f"  ✅ LIFECYCLE.md written — {len(rows)} stacks")
        print(f"  ✅ {json_target} written")
        if problems:
            print(f"  🟡 {len(problems)} consistency problem(s) — run --check for detail")
        return 0

    # ── report ───────────────────────────────────────────────────────────────
    print()
    print("  Lifecycle report")
    print()

    stale = strip_stamp(read(target)) != strip_stamp(generated)
    if stale:
        problems.append({
            "rule": "stale-report", "stack": "LIFECYCLE.md",
            "detail": "out of date with its sources — run --write",
        })

    if read(json_target) != generated_json:
        problems.append({
            "rule": "stale-report", "stack": str(json_target),
            "detail": "the operator site would render a status the sources no "
                      "longer support — run --write",
        })

    by_rule: dict[str, list[dict]] = {}
    for p in problems:
        by_rule.setdefault(p["rule"], []).append(p)

    fails = sum(1 for p in problems if WARN_RULES.isdisjoint({p["rule"]}))
    warns = len(problems) - fails

    for rule, items in sorted(by_rule.items(), key=lambda kv: -len(kv[1])):
        icon = "🟡" if rule in WARN_RULES else "🔴"
        print(f"  {icon} {rule}  ({len(items)})")
        for p in items[:8]:
            print(f"       {p['stack']}: {p['detail']}")
        if len(items) > 8:
            print(f"       … and {len(items) - 8} more")
        print()

    counts: dict[str, int] = {}
    for r in rows:
        counts[r["state"]] = counts.get(r["state"], 0) + 1
    tally = "  ·  ".join(
        f"{counts[k]} {k}" for k in reversed(STATES) if counts.get(k)
    )
    status = "❌" if fails else "✅"
    print(f"  {status} {len(rows)} stacks  ·  {tally}  ·  "
          f"{fails} failure(s)  ·  {warns} warning(s)")
    if EXCEPT:
        print(f"     {len(EXCEPT)} excepted: {', '.join(EXCEPT)}")
    print()

    if args:
        lines = [
            "## Lifecycle\n",
            f"{status} {len(rows)} stacks — {tally.replace('  ·  ', ', ')}, "
            + f"**{fails} failure(s)**, {warns} warning(s)\n",
        ]
        if problems:
            lines += ["| Level | Rule | Stack | Detail |", "|---|---|---|---|"]
            for p in problems:
                icon = "🟡 WARN" if p["rule"] in WARN_RULES else "🔴 FAIL"
                lines.append(
                    f"| {icon} | `{p['rule']}` | `{p['stack']}` | {p['detail']} |"
                )
        Path(args[0]).write_text("\n".join(lines) + "\n", encoding="utf-8")

    return 1 if (mode == "check" and fails) else 0


if __name__ == "__main__":
    sys.exit(main())
