#!/usr/bin/env python3
"""
Lifecycle report generator for secure-docker-blueprint.

Derives the per-stack lifecycle view defined in docs/standards/status-model.md
and writes it to LIFECYCLE.md. Every column is read from the file that owns the
fact — nothing here is a judgement call, and LIFECYCLE.md is never hand-edited.

Owners (see status-model.md):
  public status   category README for business/monitoring/backup,
                  root README for core/apps
  pinned version  <stack>/.env.example  (APP_TAG, else APP_IMAGE, else first pin)
  last verified   <stack>/UPSTREAM.md   ("Last verified:", legacy "Last checked:")
  backup/restore  <stack>/README.md     (presence of the corresponding section)
  restore tested  docs/maintenance.md Progress Log — no stack qualifies yet

Consistency rules (--check):

FAIL — a status claim that is not backed:
  status-mismatch      owner and root-README mirror disagree on a status
  ready-unverified     ✅ claimed while UPSTREAM.md carries no verification date
                       at all (✅ Ready criterion 8) — catches a status claim at
                       the commit that makes it, rather than months later
  stale-report         LIFECYCLE.md differs from what the sources produce

WARN — evidence probably exists, the record is in the old shape:
  legacy-stamp         ✅ with the pre-v0.5.1 `Last checked: DATE` field instead
                       of `Last verified: DATE (vX.Y.Z)`. Converting it requires
                       knowing the evidence is real, so it is never automatic.
  backup-docs-split    UPSTREAM.md documents the backup or restore procedure as
                       well. Two owners for one fact — and because this report
                       only reads the README, the stack shows up as "missing"
                       and invites a third copy. A pointer there is fine.

Usage:
  python3 scripts/ci/lifecycle-report.py            # report to stdout
  python3 scripts/ci/lifecycle-report.py --write    # regenerate LIFECYCLE.md
  python3 scripts/ci/lifecycle-report.py --check [github-summary-path]

--check exits 1 on FAIL only; the default and --write modes always exit 0.
"""

import re
import subprocess
import sys
from datetime import date
from pathlib import Path

CATEGORIES = ["core", "apps", "business", "monitoring", "backup"]

# Categories whose status is owned by their own README; the rest fall back to
# the root README. Deliberate: core/ and apps/ have no category README.
OWN_README = {"business", "monitoring", "backup"}

SYMBOLS = {"✅": "ready", "🚧": "preview", "📋": "planned", "🛡️": "ops-ready"}

# Public → internal, per the mapping table in status-model.md.
INTERNAL = {
    "planned": "—",
    "preview": "scaffolded",
    "ready": "baseline-aligned",
    "ops-ready": "ops-proven",
}

# Stacks that are structurally exempt, with the reason.
EXCEPT = {"apps/_reference": "the canonical reference itself"}

# Rules that report drift without blocking CI.
WARN_RULES = {"legacy-stamp", "backup-docs-split"}

ROW = re.compile(r"^\|.*\]\((?P<path>[a-z0-9._-]+)/\)")
STATUS_CELL = re.compile(r"\|\s*(✅|🚧|📋|🛡️)\s*\|")
VERIFIED = re.compile(r"Last\s+verified:\s*(\d{4}-\d{2}-\d{2})", re.I)
CHECKED = re.compile(r"Last\s+checked:\s*(\d{4}-\d{2}-\d{2})", re.I)
SECTION = re.compile(r"^#{2,4}\s+.*\b(backup|restore)\b", re.I)

MARKER = "<!-- generated by scripts/ci/lifecycle-report.py — do not edit by hand -->"


def read(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def plain(text: str) -> str:
    """Drop markdown emphasis so `**Last verified:**` matches like plain text."""
    return text.replace("*", "")


def statuses_from(readme: Path, prefix: str = "") -> dict[str, str]:
    """Map stack name → symbol, from every table row in a README."""
    found: dict[str, str] = {}
    for line in read(readme).splitlines():
        if prefix and f"]({prefix}" not in line:
            continue
        m = re.search(rf"\]\({re.escape(prefix)}([a-z0-9._-]+)/\)", line)
        if not m:
            continue
        cell = STATUS_CELL.search(line)
        if cell:
            found[m.group(1)] = cell.group(1)
    return found


def has_compose(stack: Path) -> bool:
    """True for a Compose stack — including ones split across per-component files."""
    return any(stack.glob("*.yml"))


def pinned_version(stack: Path) -> str:
    """The stack's primary image pin, in `VAR=value` form."""
    if not has_compose(stack):
        return "*host-installed*"
    env = read(stack / ".env.example")
    if not env:
        return "—"
    pins: dict[str, str] = {}
    for raw in env.splitlines():
        line = raw.strip()
        if line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip()
        if key.endswith(("_TAG", "_IMAGE")) and value:
            pins.setdefault(key, value)
    for preferred in ("APP_TAG", "APP_IMAGE"):
        if preferred in pins:
            return f"`{preferred}={shorten(pins[preferred])}`"
    if pins:
        key = next(iter(pins))
        return f"`{key}={shorten(pins[key])}`"
    return "—"


def shorten(value: str) -> str:
    """Abbreviate a sha256 digest so it does not blow out the table width."""
    return re.sub(r"(sha256:[0-9a-f]{12})[0-9a-f]+", r"\1…", value)


def last_verified(stack: Path) -> tuple[str, bool]:
    """(date-or-dash, is_current_format). Legacy `Last checked:` is not current."""
    text = plain(read(stack / "UPSTREAM.md"))
    if not text:
        return "—", False
    m = VERIFIED.search(text)
    if m:
        return m.group(1), True
    m = CHECKED.search(text)
    if m:
        return f"{m.group(1)} ⚠️", False
    return "—", False


# Stacks for which a `## Backup` section would be circular: the tool that performs
# the backup cannot meaningfully describe how to back itself up with itself. What
# protects them is documented in their own terms — for borgmatic, the exported
# repository key under `## Keys`.
NO_BACKUP_SECTION = {
    "backup/borgmatic": "it is the backup tool — see its `## Keys` section",
}


def doc_sections(stack: Path) -> tuple[str, str]:
    """(backup docs, restore docs).

    Counted either as a section in the stack README or as a dedicated file —
    `backup/borgmatic` keeps its procedure in RESTORE.md rather than a heading.
    """
    if str(stack) in NO_BACKUP_SECTION:
        _, restore = doc_sections_raw(stack)
        return "n/a", restore

    return doc_sections_raw(stack)


def backup_docs_elsewhere(stack: Path) -> bool:
    """True when UPSTREAM.md carries backup/restore *procedure*, not a pointer.

    The backup section belongs in the stack README — that is where the per-app
    pattern lives and the only place this script looks. An UPSTREAM.md that also
    documents the procedure is a second owner for the same fact, and because it is
    invisible here it reads as "missing" and invites someone to write a third copy.
    That happened to `apps/vaultwarden` and `business/invoiceninja`.

    A pointer back to the README is fine; a table or a command block is not.
    """
    lines = read(stack / "UPSTREAM.md").splitlines()
    inside = False
    for line in lines:
        if line.startswith("#"):
            inside = bool(SECTION.match(line))
            continue
        if inside and (line.startswith("```") or line.startswith("|")):
            return True
    return False


def doc_sections_raw(stack: Path) -> tuple[str, str]:
    has = {
        "backup": (stack / "BACKUP.md").exists(),
        "restore": (stack / "RESTORE.md").exists(),
    }
    for line in read(stack / "README.md").splitlines():
        m = SECTION.match(line)
        if m:
            has[m.group(1).lower()] = True
    return (
        "documented" if has["backup"] else "missing",
        "documented" if has["restore"] else "missing",
    )


def collect() -> tuple[list[dict], list[dict]]:
    """Return (rows, problems)."""
    root_status = {c: statuses_from(Path("README.md"), f"{c}/") for c in CATEGORIES}
    rows: list[dict] = []
    problems: list[dict] = []

    for category in CATEGORIES:
        cat_dir = Path(category)
        if not cat_dir.is_dir():
            continue

        owner_map = (
            statuses_from(cat_dir / "README.md")
            if category in OWN_README
            else root_status[category]
        )
        owner_file = (
            f"{category}/README.md" if category in OWN_README else "README.md"
        )

        for stack in sorted(p for p in cat_dir.iterdir() if p.is_dir()):
            # A component qualifies if it ships compose files — including stacks
            # split across one file per component, which have no
            # `docker-compose.yml` — or if the owning README gives it a status
            # row, which is how host-installed components like backup/borgmatic
            # get a lifecycle despite having no compose file at all.
            if not has_compose(stack) and stack.name not in owner_map:
                continue
            key = f"{category}/{stack.name}"
            if key in EXCEPT:
                continue

            symbol = owner_map.get(stack.name)
            if symbol is None:
                problems.append({
                    "rule": "status-mismatch", "stack": key,
                    "detail": f"no status row in {owner_file}",
                })
                symbol = "🚧"

            # Mirror check — only meaningful where owner and mirror differ.
            mirrored = root_status[category].get(stack.name)
            if category in OWN_README and mirrored and mirrored != symbol:
                problems.append({
                    "rule": "status-mismatch", "stack": key,
                    "detail": f"{owner_file} says {symbol}, root README says {mirrored}",
                })

            if backup_docs_elsewhere(stack):
                problems.append({
                    "rule": "backup-docs-split", "stack": key,
                    "detail": "UPSTREAM.md documents the backup or restore procedure "
                              "as well — one owner per fact; the README is the one "
                              "this report reads. Leave a pointer there instead",
                })

            public = SYMBOLS.get(symbol, "preview")
            verified, current_format = last_verified(stack)

            if public in ("ready", "ops-ready") and not current_format:
                if verified == "—":
                    problems.append({
                        "rule": "ready-unverified", "stack": key,
                        "detail": "claims ✅ but UPSTREAM.md carries no verification "
                                  "date at all (✅ Ready criterion 8)",
                    })
                else:
                    problems.append({
                        "rule": "legacy-stamp", "stack": key,
                        "detail": f"claims ✅ with the pre-v0.5.1 `Last checked: "
                                  f"{verified.split()[0]}` — needs converting to "
                                  f"`Last verified: DATE (vX.Y.Z)` once the evidence "
                                  f"is confirmed",
                    })

            backup_docs, restore_docs = doc_sections(stack)
            rows.append({
                "stack": key, "category": category, "symbol": symbol,
                "public": public, "internal": INTERNAL[public],
                "pinned": pinned_version(stack), "verified": verified,
                "backup": backup_docs, "restore": restore_docs,
            })

    return rows, problems


def render(rows: list[dict]) -> str:
    today = date.today().isoformat()
    counts: dict[str, int] = {}
    for r in rows:
        counts[r["public"]] = counts.get(r["public"], 0) + 1
    summary = " · ".join(
        f"{counts.get(k, 0)} {k}" for k in ("ops-ready", "ready", "preview")
    )

    out = [
        "# Lifecycle Overview",
        "",
        MARKER,
        "",
        f"Generated {today} from the sources named in "
        "[`docs/standards/status-model.md`](docs/standards/status-model.md). "
        "**Do not edit by hand** — run `python3 scripts/ci/lifecycle-report.py --write`.",
        "",
        f"{len(rows)} stacks: {summary}.",
        "",
        "## What the columns mean",
        "",
        "- **Public** — what an operator can rely on: `preview` · `ready` · `ops-ready`.",
        "- **Internal** — what the maintainer has established: `scaffolded` · "
        "`verified` · `baseline-aligned` · `ops-proven`.",
        "- **Last verified** — from the stack's `UPSTREAM.md`. A ⚠️ marks the legacy "
        "`Last checked:` field, which predates the current format and does not "
        "satisfy ✅ Ready criterion 8.",
        "- **Backup / Restore docs** — whether the stack README has such a section. "
        "Says nothing about whether either was ever performed. `n/a` marks a stack "
        "where the section would be circular — the backup tool cannot describe "
        "backing itself up with itself.",
        "- **Restore tested** — omitted deliberately: the blueprint holds no restore "
        "evidence for any stack yet. The column returns with the v0.7.0 backup "
        "milestone, which is what makes `ops-ready` reachable.",
        "",
    ]

    for category in CATEGORIES:
        group = [r for r in rows if r["category"] == category]
        if not group:
            continue
        out += [
            f"## `{category}/`",
            "",
            "| Stack | Public | Internal | Pinned | Last verified | Backup docs | Restore docs |",
            "|---|---|---|---|---|---|---|",
        ]
        for r in group:
            out.append(
                f"| [`{r['stack']}`]({r['stack']}/) | {r['symbol']} `{r['public']}` "
                f"| `{r['internal']}` | {r['pinned']} | {r['verified']} "
                f"| {r['backup']} | {r['restore']} |"
            )
        out.append("")

    out += [
        "## Source of truth",
        "",
        "- Stack implementation: the stack's `docker-compose.yml` + `.env.example`.",
        "- Lifecycle procedure: the stack's `README.md` and `UPSTREAM.md`.",
        "- Security baseline definition: [`docs/standards/security-baseline.md`]"
        "(docs/standards/security-baseline.md).",
        "- Status definitions and ownership: [`docs/standards/status-model.md`]"
        "(docs/standards/status-model.md).",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    args = sys.argv[1:]
    mode = "report"
    if "--write" in args:
        mode = "write"
        args.remove("--write")
    elif "--check" in args:
        mode = "check"
        args.remove("--check")

    if not Path("README.md").exists():
        print("error: run from the repository root", file=sys.stderr)
        return 2

    rows, problems = collect()
    generated = render(rows)
    target = Path("LIFECYCLE.md")

    if mode == "write":
        target.write_text(generated, encoding="utf-8")
        print(f"  ✅ LIFECYCLE.md written — {len(rows)} stacks")
        if problems:
            print(f"  🟡 {len(problems)} consistency problem(s) — run --check for detail")
        return 0

    # ── report ───────────────────────────────────────────────────────────────
    print()
    print("  Lifecycle report")
    print()

    stale = read(target) != generated
    if stale:
        problems.append({
            "rule": "stale-report", "stack": "LIFECYCLE.md",
            "detail": "out of date with its sources — run --write",
        })

    by_rule: dict[str, list[dict]] = {}
    for p in problems:
        by_rule.setdefault(p["rule"], []).append(p)

    fails = sum(1 for p in problems if WARN_RULES.isdisjoint({p["rule"]}))
    warns = len(problems) - fails

    for rule, items in sorted(by_rule.items(), key=lambda kv: -len(kv[1])):
        icon = "🟡" if rule in WARN_RULES else "🔴"
        print(f"  {icon} {rule}  ({len(items)})")
        for p in items[:8]:
            print(f"       {p['stack']}: {p['detail']}")
        if len(items) > 8:
            print(f"       … and {len(items) - 8} more")
        print()

    counts: dict[str, int] = {}
    for r in rows:
        counts[r["public"]] = counts.get(r["public"], 0) + 1
    status = "❌" if fails else "✅"
    print(f"  {status} {len(rows)} stacks  ·  "
          f"{counts.get('ready', 0)} ready  ·  {counts.get('preview', 0)} preview  ·  "
          f"{fails} failure(s)  ·  {warns} warning(s)")
    if EXCEPT:
        print(f"     {len(EXCEPT)} excepted: {', '.join(EXCEPT)}")
    print()

    if args:
        lines = [
            "## Lifecycle\n",
            f"{status} {len(rows)} stacks — {counts.get('ready', 0)} ready, "
            f"{counts.get('preview', 0)} preview, **{fails} failure(s)**, "
            f"{warns} warning(s)\n",
        ]
        if problems:
            lines += ["| Level | Rule | Stack | Detail |", "|---|---|---|---|"]
            for p in problems:
                icon = "🟡 WARN" if p["rule"] in WARN_RULES else "🔴 FAIL"
                lines.append(
                    f"| {icon} | `{p['rule']}` | `{p['stack']}` | {p['detail']} |"
                )
        Path(args[0]).write_text("\n".join(lines) + "\n", encoding="utf-8")

    return 1 if (mode == "check" and fails) else 0


if __name__ == "__main__":
    sys.exit(main())
