#!/usr/bin/env python3
"""Generate docs/security-coverage.md from the compose files.

Every coverage figure about this repository's own hardening is derivable from
the compose files the checkers already parse. Maintaining them by hand does not
work: the figures in `docs/security-verification.md` went stale twice in three
days, because a stack landing between two edits moves a denominator nobody
remembers to update. This script owns those numbers instead, the way
`lifecycle-report.py` owns `LIFECYCLE.md`.

  Scopes
    deployable   the stacks an operator deploys — the denominator for every
                 figure here
    universe     the above plus the three directories in check-structure.py's
                 EXCEPT_DIRS, which the checkers still parse although nobody
                 deploys them

  A numerator from one scope against a denominator from the other is the
  mistake this split exists to prevent, so both are stated and every figure
  names the scope it belongs to.

Stack discovery and the documented exceptions are imported rather than
repeated — check-structure.py owns which files are stacks, and
check-baseline.py owns which services are allowed to skip a hard control. A
second copy of either would drift from the checker that enforces it, which is
the failure this script exists to remove.

Usage:
  python3 scripts/ci/security-coverage.py            # report to stdout
  python3 scripts/ci/security-coverage.py --write    # regenerate the document
  python3 scripts/ci/security-coverage.py --check [github-summary-path]

--check exits 1 when the committed document no longer matches its sources.
Both other modes exit 0. Every mode exits 2 when run outside the repository
root, because the relative paths below would otherwise silently find nothing.
"""

import importlib.util
import sys
from pathlib import Path

# ── Shared discovery ──────────────────────────────────────────────────────────
# check-structure.py owns what counts as a stack and which directories are
# structural exceptions; check-baseline.py owns the documented waivers for the
# hard controls. Both are imported so a figure here can never disagree with the
# checker that enforces it.
def _load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(
        name, Path(__file__).parent / filename
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_structure = _load("check_structure", "check-structure.py")
_baseline = _load("check_baseline", "check-baseline.py")

TARGET = Path("docs/security-coverage.md")
MARKER = "<!-- generated by scripts/ci/security-coverage.py — do not edit by hand -->"

# `.env.example` is the file an operator copies; the sentinel count is about
# what they must replace before a stack starts.
ENV_EXAMPLE = ".env.example"


# ── Collection ────────────────────────────────────────────────────────────────
def services_and_files(include_excepted: bool):
    """Every (compose path, service name, service body) and every compose file.

    `include_excepted` selects the scope: False is what an operator deploys,
    True is everything the checkers parse.
    """
    excepted = set(_structure.EXCEPT_DIRS)
    files: list[tuple[Path, dict]] = []
    services: list[tuple[Path, str, dict]] = []

    for app in _structure.find_apps():
        if not include_excepted and str(app).replace("\\", "/") in excepted:
            continue
        for path in _structure.compose_files(app):
            data = _structure.compose_load(path) or {}
            files.append((path, data))
            for name, body in (data.get("services") or {}).items():
                services.append((path, name, body or {}))

    return files, services


def _has_nnp(body: dict) -> bool:
    return any("no-new-privileges" in str(opt) for opt in (body.get("security_opt") or []))


def _drops_all(body: dict) -> bool:
    return any(str(cap).upper() == "ALL" for cap in (body.get("cap_drop") or []))


def _has_limits(body: dict) -> bool:
    limits = ((body.get("deploy") or {}).get("resources") or {}).get("limits") or {}
    return bool(limits.get("memory")) and bool(limits.get("pids"))


def _exception_count(table: dict) -> int:
    """How many services a documented-exception table waives."""
    return sum(len(services) for services in table.values())


def sentinel_occurrences() -> int:
    """`__REPLACE_ME__` across the committed `.env.example` files.

    Counted over the deployable scope: it measures what an operator has to fill
    in, and nobody deploys the excepted directories.
    """
    excepted = set(_structure.EXCEPT_DIRS)
    total = 0
    for app in _structure.find_apps():
        if str(app).replace("\\", "/") in excepted:
            continue
        example = app / ENV_EXAMPLE
        if not example.exists():
            continue
        total += example.read_text(encoding="utf-8", errors="replace").count("__REPLACE_ME__")
    return total


def collect() -> dict:
    deployable_files, deployable = services_and_files(include_excepted=False)
    universe_files, universe = services_and_files(include_excepted=True)

    total = len(deployable)
    return {
        "scope": {
            "deployable": {
                "stacks": len({f.parent for f, _ in deployable_files}),
                "files": len(deployable_files),
                "services": total,
            },
            "universe": {
                "stacks": len({f.parent for f, _ in universe_files}),
                "files": len(universe_files),
                "services": len(universe),
            },
        },
        "excepted": sorted(_structure.EXCEPT_DIRS),
        "total": total,
        "files": len(deployable_files),
        "hard": {
            "no-new-privileges": sum(1 for _, _, b in deployable if _has_nnp(b)),
            "privileged": sum(1 for _, _, b in deployable if b.get("privileged") is True),
        },
        "waived": {
            "no-new-privileges": _exception_count(_baseline.NO_NEW_PRIVILEGES_EXCEPTIONS),
            "socket": _exception_count(_baseline.SOCKET_EXCEPTIONS),
            "host-mode": _exception_count(_baseline.HOST_MODE_EXCEPTIONS),
        },
        "structure": {
            "internal-network": sum(
                1
                for _, data in deployable_files
                if any((n or {}).get("internal") is True for n in (data.get("networks") or {}).values())
            ),
            "sentinels": sentinel_occurrences(),
        },
        "soft": {
            "read_only": sum(1 for _, _, b in deployable if b.get("read_only") is True),
            "cap_drop_all": sum(1 for _, _, b in deployable if _drops_all(b)),
            "user": sum(1 for _, _, b in deployable if b.get("user")),
            "limits": sum(1 for _, _, b in deployable if _has_limits(b)),
            "secrets": sum(1 for _, _, b in deployable if b.get("secrets")),
        },
    }


# ── Rendering ─────────────────────────────────────────────────────────────────
def render(facts: dict) -> str:
    total = facts["total"]
    files = facts["files"]
    dep = facts["scope"]["deployable"]
    uni = facts["scope"]["universe"]

    def of_services(n: int) -> str:
        return f"{n} / {total} services"

    def of_files(n: int) -> str:
        return f"{n} / {files} compose files"

    lines = [
        "# Security coverage",
        "",
        MARKER,
        "",
        "Every figure here is counted from the compose files, by",
        "[`scripts/ci/security-coverage.py`](../scripts/ci/security-coverage.py). It is the one",
        "owner of these numbers — [`security-verification.md`](security-verification.md) describes",
        "what each control *is* and how it is enforced, and links here rather than restating a",
        "count that moves whenever a stack lands.",
        "",
        "## Scope",
        "",
        "Two scopes exist and they differ by the directories `check-structure.py` lists in",
        "`EXCEPT_DIRS`. **Every figure below is stated against the first.**",
        "",
        "| Scope | Stacks | Compose files | Services |",
        "|---|---|---|---|",
        f"| **Deployable** | {dep['stacks']} | **{dep['files']}** | **{dep['services']}** |",
        f"| Checker universe | {uni['stacks']} | {uni['files']} | {uni['services']} |",
        "",
        "The difference is "
        + ", ".join(f"`{d}`" for d in facts["excepted"])
        + " — parsed and held to the baseline, deployed by nobody.",
        "",
        "## CI-enforced controls",
        "",
        "A merge is blocked when one of these is violated without a documented exception.",
        "",
        "| Control | Coverage | Documented exceptions |",
        "|---|---|---|",
        f"| `no-new-privileges:true` | {of_services(facts['hard']['no-new-privileges'])} "
        f"| {facts['waived']['no-new-privileges']} |",
        f"| `privileged: true` forbidden | {facts['hard']['privileged']} violation(s) "
        f"across {files} compose files | 0 |",
        f"| Docker socket via proxy only | — | {facts['waived']['socket']} |",
        f"| `network_mode: host` | — | {facts['waived']['host-mode']} |",
        "",
        "## Repository-structure controls",
        "",
        "| Control | Coverage |",
        "|---|---|",
        f"| Network isolation — a network with `internal: true` "
        f"| {of_files(facts['structure']['internal-network'])} |",
        f"| `__REPLACE_ME__` sentinels an operator must replace "
        f"| {facts['structure']['sentinels']} occurrences across `.env.example` files |",
        "",
        "## Soft controls",
        "",
        "Documented in [`standards/security-baseline.md`](standards/security-baseline.md), not",
        "CI-enforced. A low number is not automatically a gap — what an image tolerates is an",
        "image property, established by running it rather than by counting.",
        "",
        "| Control | Coverage |",
        "|---|---|",
        f"| `read_only: true` | {of_services(facts['soft']['read_only'])} |",
        f"| `cap_drop: ALL` | {of_services(facts['soft']['cap_drop_all'])} |",
        f"| Non-root `user:` | {of_services(facts['soft']['user'])} |",
        f"| Resource limits — `memory` and `pids` | {of_services(facts['soft']['limits'])} |",
        f"| Docker Secrets — a `secrets:` block | {of_services(facts['soft']['secrets'])} |",
        "",
    ]
    return "\n".join(lines)


# ── Entry point ───────────────────────────────────────────────────────────────
def main() -> int:
    args = sys.argv[1:]
    mode = "report"
    if "--write" in args:
        mode = "write"
        args.remove("--write")
    elif "--check" in args:
        mode = "check"
        args.remove("--check")

    if not Path("README.md").exists():
        print("error: run from the repository root", file=sys.stderr)
        return 2

    facts = collect()
    generated = render(facts)
    current = TARGET.read_text(encoding="utf-8", errors="replace") if TARGET.exists() else ""

    if mode == "write":
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(generated, encoding="utf-8")
        print(f"  ✅ {TARGET} written — {facts['total']} services in "
              f"{facts['files']} compose files")
        return 0

    stale = current != generated

    print()
    print("  Security coverage")
    print()
    print(f"  scope       {facts['scope']['deployable']['files']} compose files  ·  "
          f"{facts['total']} services  (deployable)")
    print(f"  hard        no-new-privileges {facts['hard']['no-new-privileges']}/{facts['total']}  ·  "
          f"privileged {facts['hard']['privileged']} violation(s)")
    print(f"  structure   internal networks {facts['structure']['internal-network']}/{facts['files']}  ·  "
          f"sentinels {facts['structure']['sentinels']}")
    print(f"  soft        read_only {facts['soft']['read_only']}  ·  "
          f"cap_drop:ALL {facts['soft']['cap_drop_all']}  ·  "
          f"user {facts['soft']['user']}  ·  secrets {facts['soft']['secrets']}")
    print()

    if mode == "check":
        if stale:
            print(f"  ❌ {TARGET} is out of date with its sources — run --write")
            print()
            summary = args[0] if args else None
            if summary:
                Path(summary).write_text(
                    f"### Security coverage\n\n`{TARGET}` is stale — run "
                    f"`python3 scripts/ci/security-coverage.py --write`.\n",
                    encoding="utf-8",
                )
            return 1
        print(f"  ✅ {TARGET} matches its sources")
        print()
        return 0

    if stale:
        print(f"  🟡 {TARGET} is out of date — run --write")
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
