#!/usr/bin/env python3
"""Fail the image scan on a CRITICAL finding that has not been recorded.

`trivy.yml` scanned every image and blocked nothing (`--exit-code 0`), so a
newly published CRITICAL could land without anyone noticing. Turning the scan
itself blocking is not an option: the repository does not build these images,
and the findings that exist today sit in the operating-system layer or in
components the image ships as upstream publishes it. A hard gate would fail
every pull request on the first day and teach people to ignore a red check.

`.ai/decisions.md` (2026-09-20) settles what to do instead: record the findings
as facts, and let the gate block **only findings that are not already
recorded**. That is what this implements. Nothing is hidden — the scan still
reports everything and `trivy-summarize.py` still counts it — and an accepted
finding is a line in a reviewed file rather than a silence.

  Keyed by repository, not by tag. `postgres:17.1` and `postgres:17.2` are the
  same upstream, and a pin bump should surface what is *new* rather than
  re-present everything. An entry whose finding has gone is reported as stale so
  it can be pruned, but it never fails the gate: an allowance for something that
  no longer exists is untidy, not dangerous.

Usage:
  trivy-gate.py --results-dir DIR              # gate: exit 1 on unrecorded
  trivy-gate.py --results-dir DIR --write      # record what the scan found
  trivy-gate.py --results-dir DIR --out FILE   # also write a GitHub summary

HIGH findings are counted by the summariser and are deliberately not gated
here. The decision names CRITICAL as the line, and a gate that fires on
everything is one nobody reads.
"""

import argparse
import json
import sys
from pathlib import Path

BASELINE = Path(".trivy-baseline.json")
SEVERITY = "CRITICAL"


def repository(image: str) -> str:
    """The image without its tag or digest.

    A colon also separates a registry from its port, so only a colon after the
    last `/` introduces a tag — `registry:5000/app` is a repository already.
    """
    base = image.split("@", 1)[0]
    head, sep, tail = base.rpartition(":")
    return head if sep and "/" not in tail else base


def findings(results_dir: Path) -> tuple[dict[str, set[str]], list[str]]:
    """{repository: {CVE, ...}} for CRITICAL findings, plus unreadable reports.

    A report that cannot be parsed is returned by name rather than skipped
    quietly: "could not be read" must never reach the gate as "found nothing".
    """
    found: dict[str, set[str]] = {}
    broken: list[str] = []
    for path in sorted(results_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            broken.append(path.name)
            continue
        image = data.get("ArtifactName")
        if not image:
            broken.append(path.name)
            continue
        for result in data.get("Results") or []:
            for vuln in result.get("Vulnerabilities") or []:
                if vuln.get("Severity") != SEVERITY:
                    continue
                cve = vuln.get("VulnerabilityID")
                if cve:
                    found.setdefault(repository(image), set()).add(cve)
    return found, broken


def load_baseline(path: Path) -> tuple[dict[str, set[str]], dict[str, str]]:
    """(accepted findings, acknowledged unscannable repositories with their reason)."""
    if not path.is_file():
        return {}, {}
    data = json.loads(path.read_text(encoding="utf-8"))
    accepted = {repo: set(cves) for repo, cves in (data.get("accepted") or {}).items()}
    return accepted, dict(data.get("unscanned") or {})


def render_baseline(found: dict[str, set[str]], scan_date: str,
                    unscanned: dict[str, str] | None = None) -> str:
    payload = {
        "_comment": (
            "CRITICAL findings accepted as known, per docs/v1-readiness-audit.md C1 and "
            ".ai/decisions.md. Keyed by image repository, not by tag. Generated by "
            "scripts/ci/trivy-gate.py --write; a finding absent from here fails the scan."
        ),
        "scan_date": scan_date,
        "accepted": {repo: sorted(cves) for repo, cves in sorted(found.items()) if cves},
        # Repositories the scanner cannot reach, each with why. An unscanned image
        # contributes no findings, so one that is not listed here would silently
        # shrink what the gate covers — it fails instead. `--write` preserves this
        # section rather than regenerating it: acknowledging an image is a
        # judgement, not something a scan can conclude.
        "unscanned": dict(sorted((unscanned or {}).items())),
    }
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-dir", required=True, type=Path)
    ap.add_argument("--baseline", type=Path, default=BASELINE)
    # An image that did not scan produces no report, so it contributes nothing to
    # the verdict. Left unsaid, "every CRITICAL is recorded" would quietly claim
    # cover it does not have — the same reason the summariser names these.
    ap.add_argument("--failures-file", type=Path,
                    help="TSV of images that did not scan, so the verdict states its reach")
    # Discovery, scanning and failure tracking must add up. An image in neither
    # list is a hole the other checks cannot see, because it leaves no trace.
    ap.add_argument("--images-total", type=int, default=0,
                    help="how many images discovery resolved; 0 skips the arithmetic")
    ap.add_argument("--write", action="store_true", help="record what this scan found")
    ap.add_argument("--scan-date", default="", help="date recorded in a --write")
    # Appended, not written: trivy-summarize.py has already put the facts in the
    # step summary and the gate's verdict belongs under them, not over them.
    ap.add_argument("--out", type=Path, help="append a GitHub step summary here")
    args = ap.parse_args()

    if not args.results_dir.is_dir():
        print(f"error: {args.results_dir} is not a directory", file=sys.stderr)
        return 2

    found, broken = findings(args.results_dir)

    if args.write:
        _, keep = load_baseline(args.baseline)
        args.baseline.write_text(
            render_baseline(found, args.scan_date, keep), encoding="utf-8")
        total = sum(len(c) for c in found.values())
        print(f"  ✅ {args.baseline} written — {total} CRITICAL finding(s) "
              f"across {len(found)} image repositories")
        return 0

    accepted, acknowledged = load_baseline(args.baseline)
    new = {repo: sorted(cves - accepted.get(repo, set())) for repo, cves in found.items()}
    new = {repo: cves for repo, cves in new.items() if cves}
    stale = {repo: sorted(cves - found.get(repo, set())) for repo, cves in accepted.items()}
    stale = {repo: cves for repo, cves in stale.items() if cves}

    total_found = sum(len(c) for c in found.values())
    total_new = sum(len(c) for c in new.values())
    scanned = len(list(args.results_dir.glob("*.json")))

    unscanned = []
    if args.failures_file and args.failures_file.is_file():
        for line in args.failures_file.read_text(encoding="utf-8").splitlines():
            if line.strip():
                unscanned.append(line.split("\t", 1)[0])

    lines = ["## Trivy CRITICAL gate", ""]
    lines.append(f"{total_found} CRITICAL finding(s) in this scan · "
                 f"{sum(len(c) for c in accepted.values())} recorded as known · "
                 f"**{total_new} not recorded**")
    lines.append("")
    unexpected = [i for i in unscanned if repository(i) not in acknowledged]
    if unscanned:
        lines.append(f"This verdict covers the images that scanned. "
                     f"{len(unscanned)} did not, and nothing here speaks for them:")
        lines.append("")
        for image in unscanned:
            why = acknowledged.get(repository(image))
            lines.append(f"- `{image}`" + (f" — acknowledged: {why}" if why else
                                           " — **not acknowledged**"))
        lines.append("")
    unaccounted = 0
    if args.images_total:
        unaccounted = args.images_total - scanned - len(unscanned)
        if unaccounted:
            lines.append(f"⚠️ **{abs(unaccounted)} image(s) in neither list** — discovery "
                         "resolved them, and they produced neither a report nor a recorded "
                         "failure. Coverage cannot be established while that is true.")
            lines.append("")

    if unexpected:
        lines.append("### An image stopped being scannable")
        lines.append("")
        lines.append("An unscanned image contributes no findings, so leaving this to a "
                     "summary line would let the gate quietly cover less than it did "
                     "yesterday. Fix the access, or record it under `unscanned` in "
                     "`.trivy-baseline.json` with the reason.")
        lines.append("")
        lines += [f"- `{image}`" for image in unexpected]
        lines.append("")

    if broken:
        lines.append("⚠️ Reports that could not be read, named rather than counted as clean:")
        lines.append("")
        lines += [f"- `{name}`" for name in broken]
        lines.append("")

    if new:
        lines.append("### Not recorded — this is what fails the gate")
        lines.append("")
        lines.append("Each is a CRITICAL with a published fix that the repository has not "
                     "yet accounted for. Raise the pin if upstream has fixed it; if it is "
                     "contained and has to stay, record it with its reason.")
        lines.append("")
        for repo, cves in sorted(new.items()):
            lines.append(f"- `{repo}` — {', '.join(cves)}")
        lines.append("")

    if stale:
        lines.append("### Recorded but no longer found")
        lines.append("")
        lines.append("Prunable with `--write`. These do not fail the gate.")
        lines.append("")
        for repo, cves in sorted(stale.items()):
            lines.append(f"- `{repo}` — {', '.join(cves)}")
        lines.append("")

    summary = "\n".join(lines)
    if args.out:
        with args.out.open("a", encoding="utf-8") as fh:
            fh.write("\n" + summary + "\n")
    print(summary)

    if broken:
        print(f"  ❌ {len(broken)} report(s) unreadable — the gate cannot vouch for them")
        return 1
    if unaccounted:
        print(f"  ❌ {unaccounted} image(s) produced neither a report nor a failure — "
              "discovery and scanning disagree, so coverage cannot be established")
        return 1
    if unexpected:
        print(f"  ❌ {len(unexpected)} image(s) did not scan and are not acknowledged")
        return 1
    if new:
        print(f"  ❌ {total_new} CRITICAL finding(s) not recorded")
        return 1
    if unscanned:
        print(f"  ✅ every CRITICAL finding is recorded ({total_found}) — "
              f"across the images that scanned; {len(unscanned)} did not")
    else:
        print(f"  ✅ every CRITICAL finding is recorded ({total_found})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
